---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 751207360325046272-5mclZL3vxyhjSgcIdAoCV5XmH6eovAk
:access_token_secret: sgCl9vDXTOpk98BXMMXgBO5TxRrTMUe0LD9BfokZ67Vtt
